export const QUERY_KEYS = {
  ALL_THE_NEWS_API: "ALL_THE_NEWS_API",
  ALL_NEWS_API: "ALL_NEWS_API",
  GUARDIAN_NEWS: "GUARDIAN_NEWS",
  NEWS_API_SOURCE: "NEWS_API_SOURCE",
  THE_NEWS_API_SOURCE: "THE_NEWS_API_SOURCE",
  
}